export const employees = [
  {
    employeeId: "5",
    createdAt: "1023-02-01T14:30:00.000Z",
    updatedAt: "2023-02-01T14:30:00.000Z",
    userId: "1",
    employeeData: {
      employeeId: "5",
      employeeDataId: "5",
      fullName: "Alan Pessoa da Costa",
      gender: "MASCULINO",
      employeeAddress: "Rua Norberto Quirino",
      employeeAddressNumber: "102",
      cep: "03474003",
      employeeNeighborhood: "Vila Antonieta",
      employeeAddressComplement: "",
      employeeAddressCity: "São Paulo",
      employeeAddressState: "SP",
      mobile: "11 99678-4256",
      email: "alan.pessoa123@gmail.com",
      fatherName: "Jose Pessoa da Costa",
      motherName: "Maria Jose Maximino da Costa",
      maritalStatus: "SOLTEIRO",
      birthday: "1990-07-05T03:00:00.000Z",
      nationality: "Brasileira",
      naturalness: "São Paulo",
      graduation: "ENSINO_FUNDAMENTAL_COMPLETO",
      skinColor: "PRETO",
    },
    employeeDocumentation: {
      documentationId: "5",
      employeeId: "5",
      rg: "49.388.834-2",
      rgEmitter: "SSP-SP",
      cpf: "402.282.708-47",
    },
  },
  {
    employeeId: "6",
    createdAt: "2023-02-01T14:30:00.000Z",
    updatedAt: "2023-02-01T14:30:00.000Z",
    userId: "1",
    employeeData: {
      employeeDataId: "6",
      employeeId: "6",
      companyNumber: 1077,
      companyName: "Associação Educacional Canadense de São Paulo",
      fullName: "Alexandre Ricardo Ciardulo Tacconi Perez",
      gender: "MASCULINO",
      employeeAddress: "Av Sabiá",
      employeeAddressNumber: "193",
      cep: "04515000",
      employeeNeighborhood: "Indianopolis",
      employeeAddressComplement: "",
      employeeAddressCity: "São Paulo",
      employeeAddressState: "SP",
      mobile: "11 98878-6851",
      email: "alexandretacconi@usp.br",
      fatherName: "Alexandre Ricardo Tacconi Milan Perez",
      motherName: "Sidneia Ciardulo",
      maritalStatus: "SOLTEIRO",
      birthday: "1999-12-09T03:00:00.000Z",
      nationality: "Brasileira",
      naturalness: "São Paulo",
      graduation: "ENSINO_SUPERIOR_COMPLETO",
      skinColor: "BRANCO",
    },
    employeeDocumentation: {
      documentationId: "6",
      employeeId: "6",
      rg: "39.930.713-8",
      rgEmitter: "SSP-SP",
      cpf: "386.159.998-80",
    },
  },
  {
    employeeId: "7",
    createdAt: "2023-02-01T14:30:00.000Z",
    updatedAt: "2023-02-01T14:30:00.000Z",
    userId: "1",
    employeeData: {
      employeeDataId: "7",
      employeeId: "7",
      companyNumber: 1077,
      companyName: "Associação Educacional Canadense de São Paulo",
      fullName: "Aline Correa",
      gender: "FEMININO",
      employeeAddress: "Rua Dona Amelia Martins",
      employeeAddressNumber: "26",
      cep: "07132510",
      employeeNeighborhood: "Cidade Martins",
      employeeAddressComplement: "Casa 3",
      employeeAddressCity: "Guarulhos",
      employeeAddressState: "SP",
      mobile: "11 93775-1459",
      email: "aline_correa.91@hotmail.com",
      fatherName: "José Carlos Correa",
      motherName: "Aparecida de Fátima Correa",
      maritalStatus: "SOLTEIRO",
      birthday: "1991-03-29T03:00:00.000Z",
      nationality: "Brasileira",
      naturalness: "Guarulhos",
      graduation: "ENSINO_SUPERIOR_COMPLETO",
      skinColor: "OUTRO",
    },
    employeeDocumentation: {
      documentationId: "7",
      employeeId: "7",
      rg: "32.218.600-6",
      rgEmitter: "SSP-SP",
      cpf: "391.219.428-97",
    },
  },
  {
    employeeId: "8",
    createdAt: "2023-02-01T14:30:00.000Z",
    updatedAt: "2023-02-01T14:30:00.000Z",
    userId: "1",
    employeeData: {
      employeeDataId: "8",
      employeeId: "8",
      companyNumber: 1077,
      companyName: "Associação Educacional Canadense de São Paulo",
      fullName: "Alline Silva Araujo dos Santos",
      gender: "FEMININO",
      employeeAddress: "Travessa  Arroio São Gonçalo",
      employeeAddressNumber: "702",
      cep: "04849500",
      employeeNeighborhood: "Pqe Resid. Cocaia",
      employeeAddressComplement: "",
      employeeAddressCity: "São Paulo",
      employeeAddressState: "SP",
      mobile: "11 5933-3833 | 11 95278-2365",
      email: "alline.araujo1994@gmail.com",
      fatherName: "Joel Araujo dos Santos",
      motherName: "Ana Rosa da Silva",
      maritalStatus: "SOLTEIRO",
      birthday: "1994-02-05T03:00:00.000Z",
      nationality: "Brasileira",
      naturalness: "São Paulo",
      graduation: "ENSINO_MEDIO_COMPLETO",
      skinColor: "OUTRO",
    },
    employeeDocumentation: {
      documentationId: "8",
      employeeId: "8",
      rg: "43.889.616-6",
      rgEmitter: "SSP-SP",
      cpf: "429.000.288-92",
    },
  },
];
