// export const employeeData = [
//   {
//     employeeId: 1,
//     employeeDataId: 1,
//     fullName: "Adriana Aparecida Alves",
//     gender: "FEMININO",
//     employeeAddress: "Avenida Brasil",
//     employeeAddressNumber: "204",
//     cep: "06352000",
//     employeeNeighborhood: "Centro",
//     employeeAddressCity: "São Paulo",
//     employeeAddressState: "SP",
//     mobile: "(19) 9979-42282",
//     email: "drizinha.alves@gmail.com",
//     fatherName: "José Marcelino Alves",
//     motherName: "Maria José Alves",
//     maritalStatus: "Solteira",
//     birthday: "1986-07-21T03:00:00.000Z",
//     nationality: "Brasileira",
//     graduation: "ENSINO_SUPERIOR_COMPLETO",
//     skinColor: "BRANCO",
//   },
//   {
//     employeeDataId: "2",
//     employeeId: "2",
//     companyNumber: 1077,
//     companyName: "Associação Educacional Canadense de São Paulo",
//     fullName: "Arthur Dent",
//     email: "arthur.dent@gmail.com",
//     tagName: "Arthur",
//     tagLastName: "Dent",
//     mobile: "(11) 9 5578-5264",
//     gender: "M",
//     fatherName: "Bartolomeu Dent",
//     motherName: "Maria Dent",
//   },
//   {
//     employeeDataId: "3",
//     employeeId: "3",
//     companyNumber: 1077,
//     companyName: "Associação Educacional Canadense de São Paulo",
//     fullName: "Ford Prefect",
//     email: "ford.perfect@gmail.com",
//     tagName: "Ford",
//     tagLastName: "Prefect",
//     mobile: "(11) 9 5578-5264",
//     gender: "M",
//     fatherName: "Bartolomeu Prefect",
//     motherName: "Maria Prefect",
//   },
//   {
//     employeeDataId: "4",
//     employeeId: "4",
//     companyNumber: 1077,
//     companyName: "Associação Educacional Canadense de São Paulo",
//     fullName: "Tricia McMillan",
//     email: "t.mcmillan@gmail.com",
//     tagName: "Tricia",
//     tagLastName: "McMillan",
//     mobile: "(11) 9 5578-5264",
//     gender: "F",
//     fatherName: "Bartolomeu McMillan",
//     motherName: "Maria McMillan",
//   },
// ];

// export const emplyeeDocumentation = [
//   {
//     documentationId: "1",
//     employeeId: "1",
//     rg: "26.544.578-4",
//     rgEmitter: "SSP-SP",
//     cpf: "323.439.688-45",
//   },
//   {
//     documentationId: "2",
//     employeeId: "2",
//     rg: "15.648.073-8",
//     rgEmitter: "SSP-SP",
//     cpf: "125.859.148-12",
//   },
//   {
//     documentationId: "3",
//     employeeId: "3",
//     rg: "15.648.073-8",
//     rgEmitter: "SSP-SP",
//     cpf: "125.859.148-12",
//   },
//   {
//     documentationId: "4",
//     employeeId: "4",
//     rg: "15.648.073-8",
//     rgEmitter: "SSP-SP",
//     cpf: "125.859.148-12",
//   },
// ];

// export const employeeContractData = [
//   {
//     contractDataId: "1",
//     employeeId: "1",
//     admissionDate: "2023-02-01T14:30:00.000Z",

//   },
//   {
//     contractDataId: "2",
//     employeeId: "2",
//     admissionDate: "2023-02-01T14:30:00.000Z",
//   },
//   {
//     contractDataId: "3",
//     employeeId: "3",
//     admissionDate: "2023-02-01T14:30:00.000Z",
//   },
//   {
//     contractDataId: "4",
//     employeeId: "4",
//     admissionDate: "2023-02-01T14:30:00.000Z",
//   },
// ];

export const employees = [
  {
    employeeId: "1",
    createdAt: "1023-02-01T14:30:00.000Z",
    updatedAt: "2023-02-01T14:30:00.000Z",
    userId: "cm4rhn9yk0000lv0oqk3m3pb3",
    employeeData: {
      employeeId: 1,
      employeeDataId: 1,
      fullName: "Adriana Aparecida Alves",
      gender: "FEMININO",
      employeeAddress: "Avenida Brasil",
      employeeAddressNumber: "204",
      cep: "06352000",
      employeeNeighborhood: "Centro",
      employeeaddressComplement: "",
      employeeAddressCity: "São Paulo",
      employeeAddressState: "SP",
      mobile: "(19) 9979-42282",
      email: "drizinha.alves@gmail.com",
      fatherName: "José Marcelino Alves",
      motherName: "Maria José Alves",
      maritalStatus: "Solteira",
      birthday: "1986-07-21T03:00:00.000Z",
      nationality: "Brasileira",
      graduation: "ENSINO_SUPERIOR_COMPLETO",
      skinColor: "BRANCO",
    },
    employeeDocumentation: {
      documentationId: "2",
      employeeId: "2",
      rg: "15.648.073-8",
      rgEmitter: "SSP-SP",
      cpf: "125.859.148-12",
    },
  },
  {
    employeeId: "2",
    createdAt: "2023-02-01T14:30:00.000Z",
    updatedAt: "2023-02-01T14:30:00.000Z",
    employeeData: {
      employeeDataId: "2",
      employeeId: "2",
      companyNumber: 1077,
      companyName: "Associação Educacional Canadense de São Paulo",
      fullName: "Arthur Dent",
      email: "arthur.dent@gmail.com",
      tagName: "Arthur",
      tagLastName: "Dent",
      mobile: "(11) 9 5578-5264",
      gender: "M",
      fatherName: "Bartolomeu Dent",
      motherName: "Maria Dent",
    },
    employeeDocumentation: {
      documentationId: "2",
      employeeId: "2",
      rg: "15.648.073-8",
      rgEmitter: "SSP-SP",
      cpf: "125.859.148-12",
    },
  },
  {
    employeeId: "3",
    createdAt: "2023-02-01T14:30:00.000Z",
    updatedAt: "2023-02-01T14:30:00.000Z",
    employeeData: {
      employeeDataId: "3",
      employeeId: "3",
      companyNumber: 1077,
      companyName: "Associação Educacional Canadense de São Paulo",
      fullName: "Ford Prefect",
      email: "ford.perfect@gmail.com",
      tagName: "Ford",
      tagLastName: "Prefect",
      mobile: "(11) 9 5578-5264",
      gender: "M",
      fatherName: "Bartolomeu Prefect",
      motherName: "Maria Prefect",
    },
    employeeDocumentation: {
      documentationId: "3",
      employeeId: "3",
      rg: "15.648.073-8",
      rgEmitter: "SSP-SP",
      cpf: "125.859.148-12",
    },
  },
  {
    employeeId: "4",
    createdAt: "2023-02-01T14:30:00.000Z",
    updatedAt: "2023-02-01T14:30:00.000Z",
    employeeData: {
      employeeDataId: "4",
      employeeId: "4",
      companyNumber: 1077,
      companyName: "Associação Educacional Canadense de São Paulo",
      fullName: "Tricia McMillan",
      email: "t.mcmillan@gmail.com",
      tagName: "Tricia",
      tagLastName: "McMillan",
      mobile: "(11) 9 5578-5264",
      gender: "F",
      fatherName: "Bartolomeu McMillan",
      motherName: "Maria McMillan",
    },
    employeeDocumentation: {
      documentationId: "4",
      employeeId: "4",
      rg: "15.648.073-8",
      rgEmitter: "SSP-SP",
      cpf: "125.859.148-12",
    },
  },
];
